### ISSUE TITLE
no file

### ISSUE THREAD

**Issue by DivyaWadehra** [PrekshaNema25/RefNet-QG#4]
bash: data_extraction_scripts/extract_embeddings.sh: No such file or directory

**Comment by PrekshaNema25** [comment]
Sorry , I am still making some changes in the repo, I have uploaded this file.

**Comment by DivyaWadehra** [comment]
not working No such file or directory: u'embeddings_sent_new/embeddings.bin'

**Comment by PrekshaNema25** [comment]
In config, I have changed the embedding_dir to embeddings/ , where the downloaded embeddings file should be present. Can you check with that?

**Comment by DivyaWadehra** [comment]
KeyError: 'Hyperparams'
